export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_USER = "AUTH_USER";

export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_DETAIL = "GET_ARTICLE_DETAIL";

export const GET_CATEGORY = "GET_CATEGORY";

export const GET_BENEFICIARY_BY_ID = "GET_BENEFICIARY_BY_ID";
export const GET_BENEFICIARY_BY_CATEGORY = "GET_BENEFICIARY_BY_CATEGORY";

export const GET_TRANSFER_BY_ID = "GET_TRANSFER_BY_ID";
export const SAVE_TRANSFER = "SAVE_TRANSFER";
